<a href="https://colab.research.google.com/github/baikAnalyst/Seoul_Software_Academy/blob/main/05.NLP/NLP_WordExpression_BOW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BoW : Bag of Words
ignore the order of appearance and express words as per frequency




In [2]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
            '오늘 동물원에서 원숭이에게 사과를 줬어']

## 1. tokenize by space

In [3]:
doc_ls = [doc.split(' ') for doc in docs]
doc_ls

[['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어'],
 ['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']]

## 2. dictionary of unique token
      2-1. generate empty dictionary

In [4]:
from collections import defaultdict

#word2id is to insert unique tokens to empty dictionary
word2id = defaultdict(lambda : len(word2id))
word2id

defaultdict(<function __main__.<lambda>()>, {})

    2-2. insert unique tokens in empty dictonary

In [6]:
for doc in doc_ls:
    print(doc)

['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어']
['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']


In [7]:
for doc in doc_ls:
    print(doc)
    for token in doc:
        word2id[token]
        print(token)

['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어']
오늘
동물원에서
코끼리
원숭이를
보고
코끼리
원숭이에게
먹이를
줬어
['오늘', '동물원에서', '원숭이에게', '사과를', '줬어']
오늘
동물원에서
원숭이에게
사과를
줬어


In [8]:
for doc in doc_ls:
    print(doc)
    for token in doc:
        word2id[token]
        print(token)
        print('\t', word2id)

['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '코끼리', '원숭이에게', '먹이를', '줬어']
오늘
	 defaultdict(<function <lambda> at 0x7fa35c41add0>, {'오늘': 0, '동물원에서': 1, '코끼리': 2, '원숭이를': 3, '보고': 4, '원숭이에게': 5, '먹이를': 6, '줬어': 7, '사과를': 8})
동물원에서
	 defaultdict(<function <lambda> at 0x7fa35c41add0>, {'오늘': 0, '동물원에서': 1, '코끼리': 2, '원숭이를': 3, '보고': 4, '원숭이에게': 5, '먹이를': 6, '줬어': 7, '사과를': 8})
코끼리
	 defaultdict(<function <lambda> at 0x7fa35c41add0>, {'오늘': 0, '동물원에서': 1, '코끼리': 2, '원숭이를': 3, '보고': 4, '원숭이에게': 5, '먹이를': 6, '줬어': 7, '사과를': 8})
원숭이를
	 defaultdict(<function <lambda> at 0x7fa35c41add0>, {'오늘': 0, '동물원에서': 1, '코끼리': 2, '원숭이를': 3, '보고': 4, '원숭이에게': 5, '먹이를': 6, '줬어': 7, '사과를': 8})
보고
	 defaultdict(<function <lambda> at 0x7fa35c41add0>, {'오늘': 0, '동물원에서': 1, '코끼리': 2, '원숭이를': 3, '보고': 4, '원숭이에게': 5, '먹이를': 6, '줬어': 7, '사과를': 8})
코끼리
	 defaultdict(<function <lambda> at 0x7fa35c41add0>, {'오늘': 0, '동물원에서': 1, '코끼리': 2, '원숭이를': 3, '보고': 4, '원숭이에게': 5, '먹이를': 6, '줬어': 7, '사과를': 8})
원숭이에게
	 defaultdict(<functi

In [9]:
word2id

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '코끼리': 2,
             '원숭이를': 3,
             '보고': 4,
             '원숭이에게': 5,
             '먹이를': 6,
             '줬어': 7,
             '사과를': 8})

## 3. BoW

In [10]:
import numpy as np
# BoW_ls =[]
for i, odc in enumerate(doc_ls):
    bow = np.zeros(len(word2id), dtype = int)
    print(bow)  # 2 x 8

[0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0]


In [11]:
import numpy as np
BoW_ls =[]
for i, doc in enumerate(doc_ls):
    bow = np.zeros(len(word2id), dtype = int)
    print(bow)
    for token in doc:
        print(token)
    #     bow[word2id[token]] +=1
    #     print(token, '=>', bow)
    # BoW_ls.append(bow.tolist())

[0 0 0 0 0 0 0 0 0]
오늘
동물원에서
코끼리
원숭이를
보고
코끼리
원숭이에게
먹이를
줬어
[0 0 0 0 0 0 0 0 0]
오늘
동물원에서
원숭이에게
사과를
줬어


In [12]:
import numpy as np
BoW_ls =[]
for i, doc in enumerate(doc_ls):
    bow = np.zeros(len(word2id), dtype = int)
    print(bow)
    for token in doc:
        print(token)
        bow[word2id[token]] +=1
        print(token, '=>', bow)
    BoW_ls.append(bow.tolist())

# {'오늘': 0, '동물원에서': 1, '코끼리': 2, '원숭이를': 3, '보고': 4,
#  '원숭이에게': 5, '먹이를': 6, '줬어': 7, '사과를': 8}

[0 0 0 0 0 0 0 0 0]
오늘
오늘 => [1 0 0 0 0 0 0 0 0]
동물원에서
동물원에서 => [1 1 0 0 0 0 0 0 0]
코끼리
코끼리 => [1 1 1 0 0 0 0 0 0]
원숭이를
원숭이를 => [1 1 1 1 0 0 0 0 0]
보고
보고 => [1 1 1 1 1 0 0 0 0]
코끼리
코끼리 => [1 1 2 1 1 0 0 0 0]
원숭이에게
원숭이에게 => [1 1 2 1 1 1 0 0 0]
먹이를
먹이를 => [1 1 2 1 1 1 1 0 0]
줬어
줬어 => [1 1 2 1 1 1 1 1 0]
[0 0 0 0 0 0 0 0 0]
오늘
오늘 => [1 0 0 0 0 0 0 0 0]
동물원에서
동물원에서 => [1 1 0 0 0 0 0 0 0]
원숭이에게
원숭이에게 => [1 1 0 0 0 1 0 0 0]
사과를
사과를 => [1 1 0 0 0 1 0 0 1]
줬어
줬어 => [1 1 0 0 0 1 0 1 1]


In [13]:
BoW_ls

[[1, 1, 2, 1, 1, 1, 1, 1, 0], [1, 1, 0, 0, 0, 1, 0, 1, 1]]

In [15]:
from IPython.core import display as ICD
import pandas as pd
sorted_vocab = sorted((value, key) for key, value in word2id.items())
print('sorted_vocab', sorted_vocab)

vocab = []
for v in sorted_vocab:
    vocab.append(v[1]) # (0, '오늘') '오늘' : tuple index#1
print('vocab', vocab)
for i in range(len(docs)) :
    print("문서{} : {}".format(i, docs[i]))
    ICD.display(pd.DataFrame([BoW_ls[i]], columns=vocab))
    print('\n\n')


sorted_vocab [(0, '오늘'), (1, '동물원에서'), (2, '코끼리'), (3, '원숭이를'), (4, '보고'), (5, '원숭이에게'), (6, '먹이를'), (7, '줬어'), (8, '사과를')]
vocab ['오늘', '동물원에서', '코끼리', '원숭이를', '보고', '원숭이에게', '먹이를', '줬어', '사과를']
문서0 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    2     1   1      1    1   1    0




문서1 : 오늘 동물원에서 원숭이에게 사과를 줬어


오늘  동물원에서  코끼리  원숭이를  보고  원숭이에게  먹이를  줬어  사과를
0   1      1    0     0   0      1    0   1    1

# BOW is not considering the order of appearance

In [33]:
# docs
docs = ['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해',
            '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']
docs

['나는 양념 치킨을 좋아해 하지만 후라이드 치킨을 싫어해', '나는 후라이드 치킨을 좋아해 하지만 양념 치킨을 싫어해']

In [34]:
# tokenize
doc_ls = [doc.split(' ') for doc in docs]
doc_ls

[['나는', '양념', '치킨을', '좋아해', '하지만', '후라이드', '치킨을', '싫어해'],
 ['나는', '후라이드', '치킨을', '좋아해', '하지만', '양념', '치킨을', '싫어해']]

In [35]:
# empty dictionary for unique tokens

from collections import defaultdict  # if dict key's value has not designated, default value is zero

word2id = defaultdict(lambda : len(word2id)) # generate empty dict
# to assign values
for doc in doc_ls:      # doc from tokenized doc_ls
    for token in doc:   # token from doc0, doc1
        word2id[token] # total 7 unique tokens
word2id

defaultdict(<function __main__.<lambda>()>,
            {'나는': 0,
             '양념': 1,
             '치킨을': 2,
             '좋아해': 3,
             '하지만': 4,
             '후라이드': 5,
             '싫어해': 6})

In [36]:
# double check dictionary value
print(word2id['양념'])
print(word2id['치킨을'])

1
2


In [37]:
import numpy as np

BoW_is = []
for i, doc in enumerate(doc_ls):
    bow = np.zeros(len(word2id), dtype=int) # generate array with zeros
    for token in doc:
        bow[word2id[token]] += 1 # replace zero with token index as per dictionary value and increase +1 if more than 1 in column
        print(bow)
    print( )
    # Bow_ls.append(bow.tolist())


[1 0 0 0 0 0 0]
[1 1 0 0 0 0 0]
[1 1 1 0 0 0 0]
[1 1 1 1 0 0 0]
[1 1 1 1 1 0 0]
[1 1 1 1 1 1 0]
[1 1 2 1 1 1 0]
[1 1 2 1 1 1 1]

[1 0 0 0 0 0 0]
[1 0 0 0 0 1 0]
[1 0 1 0 0 1 0]
[1 0 1 1 0 1 0]
[1 0 1 1 1 1 0]
[1 1 1 1 1 1 0]
[1 1 2 1 1 1 0]
[1 1 2 1 1 1 1]



In [38]:
import numpy as np

BoW_ls = []
for i, doc in enumerate(doc_ls):
    bow = np.zeros(len(word2id), dtype=int)
    for token in doc:
        bow[word2id[token]] += 1
    BoW_ls.append(bow.tolist())

In [39]:
BoW_ls

[[1, 1, 2, 1, 1, 1, 1], [1, 1, 2, 1, 1, 1, 1]]

In [40]:
import numpy as np

BoW_ls = []
for i, doc in enumerate(doc_ls):
    bow = np.zeros(len(word2id), dtype=int)
    for token in doc:
        bow[word2id[token]] += 1
    BoW_ls.append(bow.tolist())

BoW_ls

[[1, 1, 2, 1, 1, 1, 1], [1, 1, 2, 1, 1, 1, 1]]

# sklearn

In [41]:
docs = ['오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어',
            '오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어']

In [47]:
# count token frequency : CountVectorizer
from sklearn.feature_extraction.text import CountVectorizer

# declaration
count_vect = CountVectorizer()

BoW = count_vect.fit_transform(docs)
BoW.toarray()

array([[1, 1, 1, 0, 1, 1, 1, 1, 2],
       [2, 1, 1, 1, 2, 1, 2, 2, 2]])

In [48]:
from IPython.core import display as ICD

vocab = count_vect.get_feature_names_out()      # to indicate as col names
for i in range(len(docs)):                                     # repeat 2times
    print("문서{} : {}".format(i, docs[i]))               # docs[0], docs[1]
    ICD.display(pd.DataFrame([BoW.toarray()[i]], columns=vocab)) # BoW array[0], BoW array[1]
    print('\n\n')

문서0 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어


동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      1    1   1    0   1     1      1   1    2




문서1 : 오늘 동물원에서 코끼리 원숭이를 보고 코끼리 원숭이에게 먹이를 줬어 오늘 동물원에서 원숭이에게 사과를 줬어


동물원에서  먹이를  보고  사과를  오늘  원숭이를  원숭이에게  줬어  코끼리
0      2    1   1    1   2     1      2   2    2

# limits of BoW
- it doesn't considerate words' order
- Bow is sparse which means waste of vector space and cause of operation inefficiency
- word frequency does not mean the importance
- preprocessing is very critical