<a href="https://colab.research.google.com/github/baikAnalyst/Seoul_Software_Academy/blob/main/05.NLP/003_NLP_BoW_TF-IDF.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# TF-IDF
: Term Frequency - Inverse Document Frequency



In [1]:
docs = ['오늘 동물원에서 원숭이와 코끼리를 봤어',
            '동물원에서 원숭이에게 바나나를 줬어 바나나를']

In [2]:
# 1. tokenize by space

doc_ls = [doc.split(' ') for doc in docs]
doc_ls

[['오늘', '동물원에서', '원숭이와', '코끼리를', '봤어'],
 ['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']]

In [3]:
# 2. unique tokens dictionary
#   2-1. generate empy dictionary

from collections import defaultdict

word2id = defaultdict(lambda : len(word2id))
word2id

defaultdict(<function __main__.<lambda>()>, {})

In [4]:
#   2-2. imputation: unique tokens into empty dictionary which generated above

for doc in doc_ls:
    for token in doc:
        word2id[token]
        print(token)
        print('\t', word2id)
word2id

오늘
	 defaultdict(<function <lambda> at 0x7c51a0972d40>, {'오늘': 0})
동물원에서
	 defaultdict(<function <lambda> at 0x7c51a0972d40>, {'오늘': 0, '동물원에서': 1})
원숭이와
	 defaultdict(<function <lambda> at 0x7c51a0972d40>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2})
코끼리를
	 defaultdict(<function <lambda> at 0x7c51a0972d40>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2, '코끼리를': 3})
봤어
	 defaultdict(<function <lambda> at 0x7c51a0972d40>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2, '코끼리를': 3, '봤어': 4})
동물원에서
	 defaultdict(<function <lambda> at 0x7c51a0972d40>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2, '코끼리를': 3, '봤어': 4})
원숭이에게
	 defaultdict(<function <lambda> at 0x7c51a0972d40>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2, '코끼리를': 3, '봤어': 4, '원숭이에게': 5})
바나나를
	 defaultdict(<function <lambda> at 0x7c51a0972d40>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2, '코끼리를': 3, '봤어': 4, '원숭이에게': 5, '바나나를': 6})
줬어
	 defaultdict(<function <lambda> at 0x7c51a0972d40>, {'오늘': 0, '동물원에서': 1, '원숭이와': 2, '코끼리를': 3, '봤어': 4, '원숭이에게': 5, '바나나를': 6, '줬어': 7})
바나나를
	 defaultdict(<function <l

defaultdict(<function __main__.<lambda>()>,
            {'오늘': 0,
             '동물원에서': 1,
             '원숭이와': 2,
             '코끼리를': 3,
             '봤어': 4,
             '원숭이에게': 5,
             '바나나를': 6,
             '줬어': 7})

In [5]:
# 3. TF computation
#     TF = frequency of specific words' appearance / frequency of total words' appearance in documents

import numpy as np
                          # row           # col  ->  8x2 matrix
TDM = np.zeros((len(word2id), len(doc_ls)), dtype=int)

for i, doc in enumerate(doc_ls):
    print(doc)
    for token in doc:
        TDM[word2id[token], i] += 1     # token index in column
        print(token)
        print(TDM)
        print('\t')

['오늘', '동물원에서', '원숭이와', '코끼리를', '봤어']
오늘
[[1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
	
동물원에서
[[1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
	
원숭이와
[[1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
	
코끼리를
[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
	
봤어
[[1 0]
 [1 0]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]]
	
['동물원에서', '원숭이에게', '바나나를', '줬어', '바나나를']
동물원에서
[[1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]]
	
원숭이에게
[[1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]]
	
바나나를
[[1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 0]]
	
줬어
[[1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 1]
 [0 1]]
	
바나나를
[[1 0]
 [1 1]
 [1 0]
 [1 0]
 [1 0]
 [0 1]
 [0 2]
 [0 1]]
	


In [11]:
# TF computation

def computeTF(TDM):
    doc_len = len(docs)        # num of docs:2
    word_len = len(word2id) # num of unique tokens:8
    print('문서수 : ', doc_len)
    print('전체 단어수: ', word_len)

    tf = np.zeros((word_len, doc_len))
    print(tf)

    for doc_i in range(len(doc_ls)) :
        print(docs[doc_i])
        for word_i in range(len(word2id)):
            tf[word_i, doc_i] = TDM[word_i, doc_i]/TDM[:, doc_i].sum()  # TF computation
        print(tf)
    return tf

In [12]:
tf = computeTF(TDM)

문서수 :  2
전체 단어수:  8
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
오늘 동물원에서 원숭이와 코끼리를 봤어
[[0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.  0. ]
 [0.  0. ]
 [0.  0. ]]
동물원에서 원숭이에게 바나나를 줬어 바나나를
[[0.2 0. ]
 [0.2 0.2]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.  0.2]
 [0.  0.4]
 [0.  0.2]]


In [13]:
tf

array([[0.2, 0. ],
       [0.2, 0.2],
       [0.2, 0. ],
       [0.2, 0. ],
       [0.2, 0. ],
       [0. , 0.2],
       [0. , 0.4],
       [0. , 0.2]])

In [15]:
# 4. IDF computation
#     IDF = -log10(number of documents that words have appeared / total documents)

import math

def computeIDF(TDM) :
    doc_len = len(docs)  # num of docs:2
    word_len = len(word2id)
    print('문서수 : ', doc_len)
    print('전체 단어수: ', word_len)

    idf = np.zeros(word_len)
    print(idf)

    for doc_i in range(len(doc_ls)) :
        for word_i in range(len(word2id)) :  #np.count_nonzero: to count words appeared
            idf[word_i] = -math.log10(np.count_nonzero(TDM[word_i, :]) / doc_len)
    print(idf)
    return idf

# https://mathbang.net/596#gsc.tab=0

In [16]:
idf = computeIDF(TDM)
idf

문서수 :  2
전체 단어수:  8
[0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.30103 -0.       0.30103  0.30103  0.30103  0.30103  0.30103  0.30103]


array([ 0.30103, -0.     ,  0.30103,  0.30103,  0.30103,  0.30103,
        0.30103,  0.30103])

In [30]:
# 5. TF-IDF computation: TF x IDF

def computeTFIDF(TDM):
    tf = computeTF(TDM)
    idf = computeIDF(TDM).T   # inverse df -> Transpose
    tfidf = np.zeros(tf.shape)
    print( )

    for doc_i in range(len(doc_ls)) :
        print(docs[doc_i])
        for word_i in range(len(word2id)) :
            tfidf[word_i, doc_i] = tf[word_i, doc_i] * idf[word_i]

    print('TF-IDF 최종')
    print(tfidf)
    return tfidf

In [31]:
tfidf = computeTFIDF(TDM)

문서수 :  2
전체 단어수:  8
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
오늘 동물원에서 원숭이와 코끼리를 봤어
[[0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.  0. ]
 [0.  0. ]
 [0.  0. ]]
동물원에서 원숭이에게 바나나를 줬어 바나나를
[[0.2 0. ]
 [0.2 0.2]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.  0.2]
 [0.  0.4]
 [0.  0.2]]
문서수 :  2
전체 단어수:  8
[0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.30103 -0.       0.30103  0.30103  0.30103  0.30103  0.30103  0.30103]

오늘 동물원에서 원숭이와 코끼리를 봤어
동물원에서 원숭이에게 바나나를 줬어 바나나를
TF-IDF 최종
[[ 0.060206  0.      ]
 [-0.       -0.      ]
 [ 0.060206  0.      ]
 [ 0.060206  0.      ]
 [ 0.060206  0.      ]
 [ 0.        0.060206]
 [ 0.        0.120412]
 [ 0.        0.060206]]


In [32]:
tfidf

array([[ 0.060206,  0.      ],
       [-0.      , -0.      ],
       [ 0.060206,  0.      ],
       [ 0.060206,  0.      ],
       [ 0.060206,  0.      ],
       [ 0.      ,  0.060206],
       [ 0.      ,  0.120412],
       [ 0.      ,  0.060206]])

In [33]:
# 6. visualization

import pandas as pd

sorted_vocab = sorted((value, key) for key, value in word2id.items())
vocab = [v[1] for v in sorted_vocab]
print('vocab : ', vocab)
tfidf = computeTFIDF(TDM)
pd.DataFrame(tfidf.T, columns=vocab)

vocab :  ['오늘', '동물원에서', '원숭이와', '코끼리를', '봤어', '원숭이에게', '바나나를', '줬어']
문서수 :  2
전체 단어수:  8
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]
오늘 동물원에서 원숭이와 코끼리를 봤어
[[0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.  0. ]
 [0.  0. ]
 [0.  0. ]]
동물원에서 원숭이에게 바나나를 줬어 바나나를
[[0.2 0. ]
 [0.2 0.2]
 [0.2 0. ]
 [0.2 0. ]
 [0.2 0. ]
 [0.  0.2]
 [0.  0.4]
 [0.  0.2]]
문서수 :  2
전체 단어수:  8
[0. 0. 0. 0. 0. 0. 0. 0.]
[ 0.30103 -0.       0.30103  0.30103  0.30103  0.30103  0.30103  0.30103]

오늘 동물원에서 원숭이와 코끼리를 봤어
동물원에서 원숭이에게 바나나를 줬어 바나나를
TF-IDF 최종
[[ 0.060206  0.      ]
 [-0.       -0.      ]
 [ 0.060206  0.      ]
 [ 0.060206  0.      ]
 [ 0.060206  0.      ]
 [ 0.        0.060206]
 [ 0.        0.120412]
 [ 0.        0.060206]]


오늘  동물원에서      원숭이와      코끼리를        봤어     원숭이에게      바나나를        줬어
0  0.060206   -0.0  0.060206  0.060206  0.060206  0.000000  0.000000  0.000000
1  0.000000   -0.0  0.000000  0.000000  0.000000  0.060206  0.120412  0.060206

In [34]:
# sklearn

docs = ['오늘 동물원에서 원숭이와 코끼리를 봤어',
            '동물원에서 원숭이에게 바나나를 줬어 바나나를']

from sklearn.feature_extraction.text import TfidfVectorizer
tfidfV= TfidfVectorizer()
tfidfV = tfidfV.fit(docs)                              # .fit(): docs -> BoW -> tf-idf compuation for each terms -> vectorize terms in each term's index
tfidfV.transform(docs).toarray()                 # .transform(): corpus to list to iterate / .toarray(): list to numpy array
vocab = tfidfV.get_feature_names_out()

In [36]:
import pandas as pd

df = pd.DataFrame(tfidfV.transform(docs).toarray(), columns = vocab)
df

동물원에서      바나나를        봤어        오늘     원숭이에게      원숭이와        줬어  \
0  0.335176  0.000000  0.471078  0.471078  0.000000  0.471078  0.000000   
1  0.278943  0.784088  0.000000  0.000000  0.392044  0.000000  0.392044   

       코끼리를  
0  0.471078  
1  0.000000